# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
            - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peppermint

  adminer:
    image: adminer
    ports:
        - 127.0.0.1:3307:8080

  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    links: 
        -  'db'
    ports:
        - 127.0.0.1:3308:80
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
  
